sudo: false
dist: trusty
branches:
  only:
  - master
services:
  - docker
script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t docker-postgres-backup .
  - docker tag docker-postgres-backup "topmonkscom/docker-postgres-backup:build-$TRAVIS_BUILD_NUMBER"
  - docker tag docker-postgres-backup topmonkscom/docker-postgres-backup:latest
  - docker push topmonkscom/docker-postgres-backup
